AllCops:
  NewCops: enable
  SuggestExtensions: false

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
Rails/EnumHash:
  Include:
    - "**/app/models/**/*.rb"
Rails/InverseOf:
  Include:
    - "**/app/models/**/*.rb"
Rails/LexicallyScopedActionFilter:
  Include:
    - "**/app/controllers/**/*.rb"
    - "**/app/mailers/**/*.rb"
